apiVersion: v1
kind: Service
metadata:
  name: eqfinder
spec:
  selector:
    app: eqfinder
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eqfinder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eqfinder
  template:
    metadata:
      labels:
        app: eqfinder
    spec:
      containers:
        - name: app
          image: lethm/eqfinder:1.0.0
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017
          imagePullPolicy: Always